---

# v.2024-01-30

- name: 'Подготовка временного списка компьютеров (вместо hosts):'
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: 'Настройка временной группы для компьютера {{ desktop_ip }}:'
      ansible.builtin.add_host:
        groups: temp
        hostname: "{{ desktop_ip }}"

- name: 'Основная часть: Установка и настройка xrdp"'
  hosts: temp
  gather_facts: true
  become: true
  become_user: root

  vars:

    packages:
      apt:
        common:
          - mc
          - xrdp
          - xfce4-xkb-plugin
          - gnome-tweaks
          - vim
        libreoffice:
          - libreoffice

# TODO:
# - install custom soft (e.g. 1C)
# - disable screensaver
# - add users from packetfile
# - add printers
# - domain autorization

  tasks:

    - name: 'Обновление кэша установщика пакетов:'
      ansible.builtin.apt:
        update_cache: true

    # - name: 'Обновление установщика пакетов:'
    #   ansible.builtin.apt:
    #     upgrade: dist

    - name: 'Установка: Основные пакеты:'
      ansible.builtin.apt:
        name: "{{ packages.apt.common }}"
        state: present

    - name: 'Установка: LibreOffice:'
      ansible.builtin.apt:
        name: "{{ packages.apt.libreoffice }}"
        state: present

    - name: 'Установка часового пояса:'
      community.general.timezone:
        name: Europe/Moscow
      register: set_timezone
      no_log: false

    - name: 'Установка часового пояса (информация):'
      ansible.builtin.debug:
        msg:
          # - "{{ set_timezone }}"
          - "До:    {{ set_timezone.diff.before.name }}"
          - "После: {{ set_timezone.diff.after.name }}"

    - name: 'Передача дополнительного файла с описанием группы sudo:'
      ansible.builtin.copy:
        dest: /etc/sudoers.d/sudo_group
        content: |
          %sudo  ALL=(ALL) NOPASSWD: ALL
        owner: root
        group: root
        mode: "0440"

    - name: 'Отключение IPv6:'
      ansible.builtin.copy:
        dest: /etc/sysctl.d/50-ipv6disable.conf
        content: |
          net.ipv6.conf.all.disable_ipv6 = 1
          net.ipv6.conf.default.disable_ipv6 = 1
        owner: root
        group: root
        mode: "0440"

    - name: 'Исправление ошибки с чёрным экраном при входе:'
      ansible.builtin.blockinfile:
        path: /etc/xrdp/startwm.sh
        block: "{{ startwm_block }}"
        insertbefore: test -x /etc/X11/Xsession && exec /etc/X11/Xsession
        append_newline: true
      vars:
        startwm_block: |
          unset DBUS_SESSION_BUS_ADDRESS
          unset XDG_RUNTIME_DIR

    - name: 'Проверка: Отключён ли уже скринсейвер (через /etc/xrdp/reconnectwm.sh)'
      ansible.builtin.lineinfile:
        state: absent
        path: /etc/xrdp/reconnectwm.sh
        regexp: ^xset s off
      check_mode: true
      changed_when: false # Строка для журнала выполнения скрипта
      register: check_screensaver

    - name: 'Проверка: Отключён ли уже скринсейвер (проверка вывода):'
      ansible.builtin.debug:
        msg: "{{ check_screensaver }}"

    - name: 'Отключение скринсейвера (через /etc/xrdp/reconnectwm.sh):'
      when: check_screensaver.found == 0
      block:
        - name: 'Добавление строк для отключения скринсейрвера:'
          ansible.builtin.lineinfile:
            state: present
            dest: /etc/xrdp/reconnectwm.sh
            line: |
              xset s off
              xset s noblank

    - name: 'Добавление системного пользователя xrdp в группу ssl-cert:'
      ansible.builtin.user:
        name: xrdp
        groups: ssl-cert
        append: true
      notify: Restart xrdp

    - name: 'Настройка клавиатуры: Установка параметров в /etc/xrdp/xrdp_keyboard.ini'
      community.general.ini_file:
        path: /etc/xrdp/xrdp_keyboard.ini
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        no_extra_spaces: true
        mode: "0644"
      with_items:
        - { section: default_rdp_layouts, option: rdp_layout_us, value: "0x00000409" }
        - { section: default_rdp_layouts, option: rdp_layout_ru, value: "0x00000419" }
        - { section: rdp_keyboard_ru, option: keyboard_type, value: 4 }
        - { section: rdp_keyboard_ru, option: keyboard_subtype, value: 1 }
        - { section: rdp_keyboard_ru, option: model, value: pc105 }
        - { section: rdp_keyboard_ru, option: options, value: "grp:alt_shift_toggle" }
        - { section: rdp_keyboard_ru, option: rdp_layouts, value: default_rdp_layouts }
        - { section: rdp_keyboard_ru, option: layouts_map, value: layouts_map_ru }
        - { section: layouts_map_ru, option: rdp_layout_us, value: "us,ru" }
        - { section: layouts_map_ru, option: rdp_layout_ru, value: "us,ru" }

    - name: 'Настройка клавиатуры: Изменение "/etc/default/keyboard"'
      ansible.builtin.copy:
        dest: /etc/default/keyboard
        content: |
          # KEYBOARD CONFIGURATION FILE

          # Consult the keyboard(5) manual page.

          XKBMODEL="pc105"
          XKBLAYOUT="us,ru"
          XKBVARIANT=",alt_shift"
          XKBOPTIONS="grp:alt_shift_toggle,grp_led:scroll"

          BACKSPACE="guess"
        mode: "0644"
      notify: Restart xrdp

    # Замена языка ввода для окна регистрации (входа) xrdp:
    - name: 'Проверка, что файл резервной копии файла km-00000419.ini уже существует:'
      ansible.builtin.stat:
        path: /etc/xrdp/km-00000419.ini.firstbkp
      register: first_backup

    # Если резервной копии файла нет, то изготовить:
    - name: 'Резервная копия файла "/etc/xrdp/km-00000419.ini" -> "/etc/xrdp/km-00000419.ini.firstbkp":'
      ansible.builtin.copy:
        src: /etc/xrdp/km-00000419.ini
        dest: /etc/xrdp/km-00000419.ini.firstbkp
        remote_src: true
        mode: "0644"
      when: not first_backup.stat.exists

    - name: 'Копирование файла "/etc/xrdp/km-00000409.ini" -> "/etc/xrdp/km-00000419.ini":'
      ansible.builtin.copy:
        src: /etc/xrdp/km-00000409.ini
        dest: /etc/xrdp/km-00000419.ini
        remote_src: true
        mode: "0644"
      when: not first_backup.stat.exists
      notify: Restart xrdp
      # TODO: Эксперимент с раскладкой на экране логина:
      # sudo localectl set-x11-keymap us,ru pc104 "" grp:alt_shift_toggle

  handlers:
    - name: Restart xrdp
      ansible.builtin.systemd:
        name: xrdp
        state: restarted
